export default{
	menuList:[{
		name:'个人基本信息',
		icon:'cuIcon-my',
		percent:'80'
	},{
		name:'学籍信息',
		icon:'cuIcon-profile',
		percent:'70'
	},{
		name:'入学信息',
		icon:'cuIcon-newshot',
		percent:'55'
	},{
		name:'组织关系信息',
		icon:'cuIcon-peoplelist',
		percent:'60'
	},{
		name:'履历信息',
		icon:'cuIcon-news',
		percent:'65'
	},{
		name:'家庭主要成员和社会关系信息',
		icon:'cuIcon-friend',
		percent:'60'
	},]
}